Изменён алгоритм обработки номера телефона покупателя
Komtet/komtet-kassa-bitrix pull request #26
Opened 2024-07-12 11:49 UTC by AlexEfremchev

Убираем из телефона все, кроме символа '+' в начале номера.
Для телефона, который начинается на 7 без '+' добавляем '+' в начало.

2024-07-15 09:25 UTC, elatonsev commented on komtet.kassa/classes/general/KomtetKassa.php
> +        if (substr($phoneNumber, 0, 1) == "+" || substr($phoneNumber, 0, 1) == "7") {
Добавь комменты - отрезаем +, добавляем - и т.д. Тяжело это читать потом.

2024-07-15 09:26 UTC, elatonsev approved these changes

2024-07-16 07:33 UTC, a1723 requested changes

2024-07-16 07:33 UTC, a1723 commented on komtet.kassa/classes/general/KomtetKassa.php
> +            $phoneNumber = preg_replace('/[^0-9]/', '', $phoneNumber);
можно вынести эту строчку наверх из под if, а в if оставить только верхнее условие
```php
$phoneNumber = preg_replace('/[^0-9]/', '', $phoneNumber);
```

2024-07-17 06:21 UTC, a1723 requested changes

2024-07-17 06:21 UTC, a1723 commented on komtet.kassa/classes/general/KomtetKassa.php
> +        if ($userPhone) {
на 418 строчке уже есть такой if.
Преобразование номера телефона можно положить под него чтобы не делать ещё один такой же if ?

2024-07-18 05:45 UTC, a1723 approved these changes

2024-07-18 05:45 UTC, a1723 commented on komtet.kassa/classes/general/KomtetKassa.php
> +
строка какая-то лишняя

2024-07-18 08:12 UTC, zeleng approved these changes

2024-07-22 08:42 UTC, merged